version: "3"
services:
  gateway:
    build: ./services/gateway/.
    ports:
     - 8000:8000
    links:
      - library
      - rating
      - reservation
    environment:
      - LIB_SERVICE_URL=library:50051
      - RATING_SERVICE_URL=rating:50053
      - RESERVATION_SERVICE_URL=reservation:50052
    command:
      - ./gateway

  library:
    build: ./services/library/.
    ports:
      - 50051:50051
    command:
      - ./library

  reservation:
    build: ./services/reservation/.
    ports:
      - 50052:50052
    command:
      - ./reservation

  rating:
    build: ./services/rating/.
    ports:
      - 50053:50053
    command:
      - ./rating