version: "3"
services:
  gateway:
    build: ./services/gateway/.
    ports:
     - 8000:8000
    links:
      - library
      - rating
      - reservation

  library:
    build: ./services/library/.
    ports:
      - 50051:50051

  reservation:
    build: ./services/reservation/.
    ports:
      - 50052:50052

  rating:
    build: ./services/rating/.
    ports:
      - 50053:50053