version: "3"
services:
  nginx:
    build: ./internal/nginx/.
    ports:
     - 80:80
    links:
      - library
      - rating
      - reservation

  library:
    build: ./services/library/.
    ports:
      - 8100:8100

  reservation:
    build: ./services/reservation/.
    ports:
      - 8200:8200

  rating:
    build: ./services/rating/.
    ports:
      - 8300:8300