// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: reservation/reservation.proto

package reservation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReturnBookRequest_Condition int32

const (
	ReturnBookRequest_EXCELLENT ReturnBookRequest_Condition = 0
	ReturnBookRequest_GOOD      ReturnBookRequest_Condition = 1
	ReturnBookRequest_BAD       ReturnBookRequest_Condition = 2
)

// Enum value maps for ReturnBookRequest_Condition.
var (
	ReturnBookRequest_Condition_name = map[int32]string{
		0: "EXCELLENT",
		1: "GOOD",
		2: "BAD",
	}
	ReturnBookRequest_Condition_value = map[string]int32{
		"EXCELLENT": 0,
		"GOOD":      1,
		"BAD":       2,
	}
)

func (x ReturnBookRequest_Condition) Enum() *ReturnBookRequest_Condition {
	p := new(ReturnBookRequest_Condition)
	*p = x
	return p
}

func (x ReturnBookRequest_Condition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReturnBookRequest_Condition) Descriptor() protoreflect.EnumDescriptor {
	return file_reservation_reservation_proto_enumTypes[0].Descriptor()
}

func (ReturnBookRequest_Condition) Type() protoreflect.EnumType {
	return &file_reservation_reservation_proto_enumTypes[0]
}

func (x ReturnBookRequest_Condition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReturnBookRequest_Condition.Descriptor instead.
func (ReturnBookRequest_Condition) EnumDescriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{1, 0}
}

type TakeBookResponse_Status int32

const (
	TakeBookResponse_RENTED   TakeBookResponse_Status = 0
	TakeBookResponse_RETURNED TakeBookResponse_Status = 1
	TakeBookResponse_EXPIRED  TakeBookResponse_Status = 2
)

// Enum value maps for TakeBookResponse_Status.
var (
	TakeBookResponse_Status_name = map[int32]string{
		0: "RENTED",
		1: "RETURNED",
		2: "EXPIRED",
	}
	TakeBookResponse_Status_value = map[string]int32{
		"RENTED":   0,
		"RETURNED": 1,
		"EXPIRED":  2,
	}
)

func (x TakeBookResponse_Status) Enum() *TakeBookResponse_Status {
	p := new(TakeBookResponse_Status)
	*p = x
	return p
}

func (x TakeBookResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TakeBookResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_reservation_reservation_proto_enumTypes[1].Descriptor()
}

func (TakeBookResponse_Status) Type() protoreflect.EnumType {
	return &file_reservation_reservation_proto_enumTypes[1]
}

func (x TakeBookResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TakeBookResponse_Status.Descriptor instead.
func (TakeBookResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{4, 0}
}

type ReservationFetchResponseItem_Status int32

const (
	ReservationFetchResponseItem_RENTED   ReservationFetchResponseItem_Status = 0
	ReservationFetchResponseItem_RETURNED ReservationFetchResponseItem_Status = 1
	ReservationFetchResponseItem_EXPIRED  ReservationFetchResponseItem_Status = 2
)

// Enum value maps for ReservationFetchResponseItem_Status.
var (
	ReservationFetchResponseItem_Status_name = map[int32]string{
		0: "RENTED",
		1: "RETURNED",
		2: "EXPIRED",
	}
	ReservationFetchResponseItem_Status_value = map[string]int32{
		"RENTED":   0,
		"RETURNED": 1,
		"EXPIRED":  2,
	}
)

func (x ReservationFetchResponseItem_Status) Enum() *ReservationFetchResponseItem_Status {
	p := new(ReservationFetchResponseItem_Status)
	*p = x
	return p
}

func (x ReservationFetchResponseItem_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReservationFetchResponseItem_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_reservation_reservation_proto_enumTypes[2].Descriptor()
}

func (ReservationFetchResponseItem_Status) Type() protoreflect.EnumType {
	return &file_reservation_reservation_proto_enumTypes[2]
}

func (x ReservationFetchResponseItem_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReservationFetchResponseItem_Status.Descriptor instead.
func (ReservationFetchResponseItem_Status) EnumDescriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{6, 0}
}

type GetReservationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResUid string `protobuf:"bytes,1,opt,name=resUid,proto3" json:"resUid,omitempty"`
}

func (x *GetReservationRequest) Reset() {
	*x = GetReservationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationRequest) ProtoMessage() {}

func (x *GetReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationRequest.ProtoReflect.Descriptor instead.
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *GetReservationRequest) GetResUid() string {
	if x != nil {
		return x.ResUid
	}
	return ""
}

type ReturnBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReservationUid string                      `protobuf:"bytes,1,opt,name=reservationUid,proto3" json:"reservationUid,omitempty"`
	Name           string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Condition      ReturnBookRequest_Condition `protobuf:"varint,3,opt,name=condition,proto3,enum=library.ReturnBookRequest_Condition" json:"condition,omitempty"`
	Date           *timestamppb.Timestamp      `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
}

func (x *ReturnBookRequest) Reset() {
	*x = ReturnBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnBookRequest) ProtoMessage() {}

func (x *ReturnBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnBookRequest.ProtoReflect.Descriptor instead.
func (*ReturnBookRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *ReturnBookRequest) GetReservationUid() string {
	if x != nil {
		return x.ReservationUid
	}
	return ""
}

func (x *ReturnBookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReturnBookRequest) GetCondition() ReturnBookRequest_Condition {
	if x != nil {
		return x.Condition
	}
	return ReturnBookRequest_EXCELLENT
}

func (x *ReturnBookRequest) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

type ReturnBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *ReturnBookResponse) Reset() {
	*x = ReturnBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReturnBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnBookResponse) ProtoMessage() {}

func (x *ReturnBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnBookResponse.ProtoReflect.Descriptor instead.
func (*ReturnBookResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *ReturnBookResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type TakeBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name       string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BookUid    string                 `protobuf:"bytes,2,opt,name=bookUid,proto3" json:"bookUid,omitempty"`
	LibraryUid string                 `protobuf:"bytes,3,opt,name=libraryUid,proto3" json:"libraryUid,omitempty"`
	TillDate   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=tillDate,proto3" json:"tillDate,omitempty"`
}

func (x *TakeBookRequest) Reset() {
	*x = TakeBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TakeBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeBookRequest) ProtoMessage() {}

func (x *TakeBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeBookRequest.ProtoReflect.Descriptor instead.
func (*TakeBookRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{3}
}

func (x *TakeBookRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TakeBookRequest) GetBookUid() string {
	if x != nil {
		return x.BookUid
	}
	return ""
}

func (x *TakeBookRequest) GetLibraryUid() string {
	if x != nil {
		return x.LibraryUid
	}
	return ""
}

func (x *TakeBookRequest) GetTillDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TillDate
	}
	return nil
}

type TakeBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReservationUid string                  `protobuf:"bytes,1,opt,name=reservationUid,proto3" json:"reservationUid,omitempty"`
	Status         TakeBookResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=library.TakeBookResponse_Status" json:"status,omitempty"`
	StartDate      *timestamppb.Timestamp  `protobuf:"bytes,3,opt,name=startDate,proto3" json:"startDate,omitempty"`
	TillDate       *timestamppb.Timestamp  `protobuf:"bytes,4,opt,name=tillDate,proto3" json:"tillDate,omitempty"`
	LibraryUid     string                  `protobuf:"bytes,5,opt,name=libraryUid,proto3" json:"libraryUid,omitempty"`
	BookUid        string                  `protobuf:"bytes,6,opt,name=bookUid,proto3" json:"bookUid,omitempty"`
}

func (x *TakeBookResponse) Reset() {
	*x = TakeBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TakeBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeBookResponse) ProtoMessage() {}

func (x *TakeBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeBookResponse.ProtoReflect.Descriptor instead.
func (*TakeBookResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{4}
}

func (x *TakeBookResponse) GetReservationUid() string {
	if x != nil {
		return x.ReservationUid
	}
	return ""
}

func (x *TakeBookResponse) GetStatus() TakeBookResponse_Status {
	if x != nil {
		return x.Status
	}
	return TakeBookResponse_RENTED
}

func (x *TakeBookResponse) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *TakeBookResponse) GetTillDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TillDate
	}
	return nil
}

func (x *TakeBookResponse) GetLibraryUid() string {
	if x != nil {
		return x.LibraryUid
	}
	return ""
}

func (x *TakeBookResponse) GetBookUid() string {
	if x != nil {
		return x.BookUid
	}
	return ""
}

type ReservationFetchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ReservationFetchRequest) Reset() {
	*x = ReservationFetchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReservationFetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationFetchRequest) ProtoMessage() {}

func (x *ReservationFetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationFetchRequest.ProtoReflect.Descriptor instead.
func (*ReservationFetchRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{5}
}

func (x *ReservationFetchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReservationFetchResponseItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ReservationUid string                              `protobuf:"bytes,1,opt,name=reservationUid,proto3" json:"reservationUid,omitempty"`
	LibraryUid     string                              `protobuf:"bytes,2,opt,name=libraryUid,proto3" json:"libraryUid,omitempty"`
	BookUid        string                              `protobuf:"bytes,3,opt,name=bookUid,proto3" json:"bookUid,omitempty"`
	Status         ReservationFetchResponseItem_Status `protobuf:"varint,4,opt,name=status,proto3,enum=library.ReservationFetchResponseItem_Status" json:"status,omitempty"`
	StartDate      *timestamppb.Timestamp              `protobuf:"bytes,5,opt,name=startDate,proto3" json:"startDate,omitempty"`
	TillDate       *timestamppb.Timestamp              `protobuf:"bytes,6,opt,name=tillDate,proto3" json:"tillDate,omitempty"`
}

func (x *ReservationFetchResponseItem) Reset() {
	*x = ReservationFetchResponseItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReservationFetchResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationFetchResponseItem) ProtoMessage() {}

func (x *ReservationFetchResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationFetchResponseItem.ProtoReflect.Descriptor instead.
func (*ReservationFetchResponseItem) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{6}
}

func (x *ReservationFetchResponseItem) GetReservationUid() string {
	if x != nil {
		return x.ReservationUid
	}
	return ""
}

func (x *ReservationFetchResponseItem) GetLibraryUid() string {
	if x != nil {
		return x.LibraryUid
	}
	return ""
}

func (x *ReservationFetchResponseItem) GetBookUid() string {
	if x != nil {
		return x.BookUid
	}
	return ""
}

func (x *ReservationFetchResponseItem) GetStatus() ReservationFetchResponseItem_Status {
	if x != nil {
		return x.Status
	}
	return ReservationFetchResponseItem_RENTED
}

func (x *ReservationFetchResponseItem) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *ReservationFetchResponseItem) GetTillDate() *timestamppb.Timestamp {
	if x != nil {
		return x.TillDate
	}
	return nil
}

type ReservationFetchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ReservationFetchResponseItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *ReservationFetchResponse) Reset() {
	*x = ReservationFetchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reservation_reservation_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReservationFetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationFetchResponse) ProtoMessage() {}

func (x *ReservationFetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationFetchResponse.ProtoReflect.Descriptor instead.
func (*ReservationFetchResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{7}
}

func (x *ReservationFetchResponse) GetItems() []*ReservationFetchResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_reservation_reservation_proto protoreflect.FileDescriptor

var file_reservation_reservation_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x55, 0x69, 0x64, 0x22, 0xf2, 0x01, 0x0a, 0x11, 0x52,
	0x65, 0x74, 0x75, 0x72, 0x6e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x42, 0x0a, 0x09,
	0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x24, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x64,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x64, 0x61, 0x74, 0x65,
	0x22, 0x2d, 0x0a, 0x09, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0d, 0x0a,
	0x09, 0x45, 0x58, 0x43, 0x45, 0x4c, 0x4c, 0x45, 0x4e, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04,
	0x47, 0x4f, 0x4f, 0x44, 0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x42, 0x41, 0x44, 0x10, 0x02, 0x22,
	0x24, 0x0a, 0x12, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x97, 0x01, 0x0a, 0x0f, 0x54, 0x61, 0x6b, 0x65, 0x42, 0x6f,
	0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x62, 0x6f, 0x6f, 0x6b, 0x55, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x62, 0x72, 0x61,
	0x72, 0x79, 0x55, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69, 0x62,
	0x72, 0x61, 0x72, 0x79, 0x55, 0x69, 0x64, 0x12, 0x36, 0x0a, 0x08, 0x74, 0x69, 0x6c, 0x6c, 0x44,
	0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08, 0x74, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x22,
	0xd1, 0x02, 0x0a, 0x10, 0x54, 0x61, 0x6b, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x6c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x54, 0x61, 0x6b, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65,
	0x12, 0x36, 0x0a, 0x08, 0x74, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x08,
	0x74, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x62, 0x72,
	0x61, 0x72, 0x79, 0x55, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6c, 0x69,
	0x62, 0x72, 0x61, 0x72, 0x79, 0x55, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x6f, 0x6f, 0x6b,
	0x55, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f, 0x6f, 0x6b, 0x55,
	0x69, 0x64, 0x22, 0x2f, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06,
	0x52, 0x45, 0x4e, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x54, 0x55,
	0x52, 0x4e, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45,
	0x44, 0x10, 0x02, 0x22, 0x2d, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xe9, 0x02, 0x0a, 0x1c, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x55, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x72, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x55, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x6c,
	0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x55, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x55, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x6f, 0x6f, 0x6b, 0x55, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x6f,
	0x6f, 0x6b, 0x55, 0x69, 0x64, 0x12, 0x44, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2c, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x38, 0x0a, 0x09, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x36, 0x0a, 0x08, 0x74, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x08, 0x74, 0x69, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x65, 0x22, 0x2f, 0x0a,
	0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4e, 0x54, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x45, 0x54, 0x55, 0x52, 0x4e, 0x45, 0x44, 0x10,
	0x01, 0x12, 0x0b, 0x0a, 0x07, 0x45, 0x58, 0x50, 0x49, 0x52, 0x45, 0x44, 0x10, 0x02, 0x22, 0x57,
	0x0a, 0x18, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x65, 0x74,
	0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b, 0x0a, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x6c, 0x69, 0x62, 0x72,
	0x61, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x32, 0xcf, 0x02, 0x0a, 0x12, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x58,
	0x0a, 0x11, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x20, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x52, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x65, 0x74, 0x63, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x54, 0x61, 0x6b, 0x65,
	0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x18, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x54,
	0x61, 0x6b, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19,
	0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x54, 0x61, 0x6b, 0x65, 0x42, 0x6f, 0x6f,
	0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x52, 0x65, 0x74,
	0x75, 0x72, 0x6e, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1a, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72,
	0x79, 0x2e, 0x52, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x52, 0x65,
	0x74, 0x75, 0x72, 0x6e, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x57, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1e, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6c, 0x69, 0x62, 0x72, 0x61, 0x72, 0x79, 0x2e, 0x52, 0x65, 0x73,
	0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x42, 0x20, 0x5a, 0x1e, 0x6c, 0x69, 0x62,
	0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x72, 0x65, 0x73, 0x65, 0x72, 0x76, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_reservation_reservation_proto_rawDescOnce sync.Once
	file_reservation_reservation_proto_rawDescData = file_reservation_reservation_proto_rawDesc
)

func file_reservation_reservation_proto_rawDescGZIP() []byte {
	file_reservation_reservation_proto_rawDescOnce.Do(func() {
		file_reservation_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(file_reservation_reservation_proto_rawDescData)
	})
	return file_reservation_reservation_proto_rawDescData
}

var file_reservation_reservation_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_reservation_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_reservation_reservation_proto_goTypes = []interface{}{
	(ReturnBookRequest_Condition)(0),         // 0: library.ReturnBookRequest.Condition
	(TakeBookResponse_Status)(0),             // 1: library.TakeBookResponse.Status
	(ReservationFetchResponseItem_Status)(0), // 2: library.ReservationFetchResponseItem.Status
	(*GetReservationRequest)(nil),            // 3: library.GetReservationRequest
	(*ReturnBookRequest)(nil),                // 4: library.ReturnBookRequest
	(*ReturnBookResponse)(nil),               // 5: library.ReturnBookResponse
	(*TakeBookRequest)(nil),                  // 6: library.TakeBookRequest
	(*TakeBookResponse)(nil),                 // 7: library.TakeBookResponse
	(*ReservationFetchRequest)(nil),          // 8: library.ReservationFetchRequest
	(*ReservationFetchResponseItem)(nil),     // 9: library.ReservationFetchResponseItem
	(*ReservationFetchResponse)(nil),         // 10: library.ReservationFetchResponse
	(*timestamppb.Timestamp)(nil),            // 11: google.protobuf.Timestamp
}
var file_reservation_reservation_proto_depIdxs = []int32{
	0,  // 0: library.ReturnBookRequest.condition:type_name -> library.ReturnBookRequest.Condition
	11, // 1: library.ReturnBookRequest.date:type_name -> google.protobuf.Timestamp
	11, // 2: library.TakeBookRequest.tillDate:type_name -> google.protobuf.Timestamp
	1,  // 3: library.TakeBookResponse.status:type_name -> library.TakeBookResponse.Status
	11, // 4: library.TakeBookResponse.startDate:type_name -> google.protobuf.Timestamp
	11, // 5: library.TakeBookResponse.tillDate:type_name -> google.protobuf.Timestamp
	2,  // 6: library.ReservationFetchResponseItem.status:type_name -> library.ReservationFetchResponseItem.Status
	11, // 7: library.ReservationFetchResponseItem.startDate:type_name -> google.protobuf.Timestamp
	11, // 8: library.ReservationFetchResponseItem.tillDate:type_name -> google.protobuf.Timestamp
	9,  // 9: library.ReservationFetchResponse.items:type_name -> library.ReservationFetchResponseItem
	8,  // 10: library.ReservationService.FetchReservations:input_type -> library.ReservationFetchRequest
	6,  // 11: library.ReservationService.TakeBook:input_type -> library.TakeBookRequest
	4,  // 12: library.ReservationService.ReturnBook:input_type -> library.ReturnBookRequest
	3,  // 13: library.ReservationService.GetReservation:input_type -> library.GetReservationRequest
	10, // 14: library.ReservationService.FetchReservations:output_type -> library.ReservationFetchResponse
	7,  // 15: library.ReservationService.TakeBook:output_type -> library.TakeBookResponse
	5,  // 16: library.ReservationService.ReturnBook:output_type -> library.ReturnBookResponse
	9,  // 17: library.ReservationService.GetReservation:output_type -> library.ReservationFetchResponseItem
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_reservation_reservation_proto_init() }
func file_reservation_reservation_proto_init() {
	if File_reservation_reservation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reservation_reservation_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetReservationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReturnBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TakeBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TakeBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReservationFetchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReservationFetchResponseItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reservation_reservation_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReservationFetchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reservation_reservation_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reservation_reservation_proto_goTypes,
		DependencyIndexes: file_reservation_reservation_proto_depIdxs,
		EnumInfos:         file_reservation_reservation_proto_enumTypes,
		MessageInfos:      file_reservation_reservation_proto_msgTypes,
	}.Build()
	File_reservation_reservation_proto = out.File
	file_reservation_reservation_proto_rawDesc = nil
	file_reservation_reservation_proto_goTypes = nil
	file_reservation_reservation_proto_depIdxs = nil
}
