name: GitHub Classroom Workflow
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Autograding
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.17
      - name: Tests
        run: |
          cd ./services/gateway/internal
          go mod tidy
          go test ./...
          cd ../../library/internal/
          go mod tidy
          go test ./...
          cd ../../rating/internal/
          go mod tidy
          go test ./...
          cd ../../reservation/internal/
          go mod tidy
          go test ./...
          cd ../../..

#      - name: Run API Tests
#        id: run-newman
#        uses: anthonyvscode/newman-action@v1
#        with:
#          collection: postman/[inst] Lab1.postman_collection.json
#          environment: postman/[inst][heroku] Lab1.postman_environment.json
#          delayRequest: 50
#          reporters: cli

      - name: Run API Tests
        id: run-newman1
        uses: anthonyvscode/newman-action@v1
        with:
          collection: v4/postman/[rsoi] postman_collection.json
          environment: v4/postman/[rsoi][heroku] postman_environment.json
          delayRequest: 50
          reporters: cli

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true